theme = "semi-native"
icons = "awesome"

[[block]]
block = "backlight"
device = "intel_backlight"
minimum = 15
maximum = 100
cycle = [50, 30, 20, 10]


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "battery"
driver = "upower"
interval = 20

[[block]]
block = "cpu"
format = "{utilization}"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " {layout}"
[block.mappings]
"English (US)" = "EN"
"Russian (N/A)" = "RU"
"Ukrainian (N/A)" = "UA"

[[block]]
block = "time"
format = "%a %d/%m %R"
interval = 60
